sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ZoaRqGiPb8xlmNgR+Se30rinoJstxahe1ZqtUE6NLV9E7ohzby/INoL33CsXojymzHR5JstzoZM+cSN9QmG5R7IXGQD67KQqoMJ71OoYcJrQJZgGkuvBPe4vJeabhU0niBukFnsjkGCOa4r8ZbfiNLt0W2fA+voBHSakxpud+W0USkyH11Ww0dWlJYEJt+epHg6aWKPIMlKqwqEVXtFbjI2JtX2Z67mquiYV8gMDf8TMbM1RmzlKOHZCWAjXkKYQzFfSQs/vSsN3XOTV+cilFnc7tAj3ZXwZB+BumhMjgpOa7eU988AfEGrVx1CzbY7u+u+FbJXEsNT03kI9NmcfYytZpoj1/6V2wfz/DZzz0mNYm7PzPLMZ2InsMVwaiozPRaBbpJH1d1XpsluoXeYFQbHzsXRYmbsRvuHV6Sw43S9z0h1juzY2zCFuqv5ZxKIaLWu9gbOUHU8H1Igu+HrwjP589jXKHHSabXAXIiunh6m7K4FILrQ/EvsiyX659LaOq9nX+igjD0qSuUZlBNoylhMUs5q6ycrrOs/epaSg97MiTmQrbWuj691N9tho1hRhFaHcC3tdtwKCpROKteZqeInItiMbmN5PpSSJ1ehCtN4ynnU5wTrq2BGiy+f+zf0ae3NWW5bAwhYkUSif7DuAouSRsjsnzriONqo8TyoXXZM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Ainsi-Parlait-Zarathoustra_5258
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy